# fly.toml app configuration file generated for sbb2405-deploy on 2024-05-23T13:27:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sbb2405-deploy'
primary_region = "nrt"

[build]


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[env]
DB_URL = "jdbc:postgresql://sbb2405-deploy-db.internal:5432/postgres"
DB_USERNAME = "postgres"
DB_PASSWORD = "Qehlep6VIWajrSw"

HOSTNAME = "0.0.0.0"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
