server:
  address: 0.0.0.0
  port: 8080

spring:
  profiles:
    active: prod
    include: secret
  datasource:
    url: jdbc:postgresql://sbb2405-deploy-db.internal:5432/postgres
    username: postgres
    password: Qehlep6VIWajrSw
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE
