spring:
  datasource:
    url: jdbc:postgresql://sbb2405-deploy-db.internal:5432/postgres
    username: postgres
    password: Qehlep6VIWajrSw
    driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
  properties:
    hibernate:
      show_sql: false
      format_sql: false
      use_sql_comments: false

